# APPLICATION KEYBINDINGS

bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod SHIFT, RETURN, exec, [float; size 800 450; center] $terminal
bind = $mainMod, E, exec, alacritty -e yazi
bind = $mainMod SHIFT, E, exec, thunar
bind = $mainMod, B, exec, $browser
bind = $mainMod, P, exec, kitty --class ncmpcpp -e ncmpcpp & ~/.config/ncmpcpp/cover-float.sh
bind = $mainMod, X, exec, hyprlock
bind = $mainMod, A, exec, pgrep wofi || $launcher
bind = $mainMod SHIFT, A, exec, ~/.config/scripts/utils/util-launcher.sh
bind = $mainMod, N, exec, swaync-client -t
bind = $mainMod, Escape, exec, pgrep wlogout || wlogout -b 2
bind = $mainMod SHIFT, P, exec, ~/.config/scripts/media/random-album.sh
bind = $mainMod CTRL, P, exec, mpc toggle
bind = $mainMod, W, exec, ~/.config/scripts/theme/wallpaper-rotate.sh
bind = $mainMod SHIFT, W, exec, waytrogen
bind = $mainMod ALT, W, exec, pgrep -x waybar >/dev/null && killall waybar || waybar &
bind = $mainMod ALT, B, exec, bongocat -c ~/.config/bongocat/bongo.conf --toggle
bind = $mainMod ALT, N, exec, ~/.config/scripts/restart-swaync.sh
bind = $mainMod, V, exec, ~/.config/scripts/utils/cliphist-paste.sh
bind = $mainMod, F5, exec, ~/.config/scripts/utils/hyprsunset-toggle.sh
