# AUTOSTART APPLICATIONS
exec-once = waybar
exec-once = hypridle
exec-once = hyprpolkitagent
exec-once = udiskie
exec-once = swaync
exec-once = easyeffects --gapplication-service
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = swww init
exec-once = waytrogen -r
exec-once = hyprswitch init --show-title --size-factor 5 --workspaces-per-row 4 --custom-css $configDir/hyprswitch.css
# mpd and mpd-mpris are managed by systemd user services

# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Workspace-to-monitor bindings are set in monitors.conf
