# PLUGIN CONFIGURATION
plugin = /usr/lib/libhyprexpo.so

plugin {
    hyprexpo {
        columns = 2
        gap_size = 5
        bg_col = rgb(111111)
        workspace_method = first 1

        enable_gesture = false
    }
}