source = $HOME/.config/hypr/config/variables.conf

# FLOATING WINDOW RULES
windowrule = match:class ^(xdg-desktop-portal-gtk)$, float on
windowrule = match:class ^($terminal)$, match:title ^(top)$, float on
windowrule = match:class ^($terminal)$, match:title ^(btm)$, float on
windowrule = match:class ^($terminal)$, match:title ^(htop)$, float on
windowrule = match:class ^(thunar)$, match:title ^(Rename.*)$, float on
windowrule = match:class ^(Thunar)$, match:title ^(Rename.*)$, float on
windowrule = match:class ^(org.gnome.FileRoller)$, float on
windowrule = match:class ^(qt5ct)$, float on
windowrule = match:class ^(qt6ct)$, float on
windowrule = match:class ^(nwg-look)$, float on
windowrule = match:class ^(nwg-displays)$, float on
windowrule = match:class ^(org.pulseaudio.pavucontrol)$, float on
windowrule = match:class ^(blueman-manager)$, float on
windowrule = match:class ^(nm-connection-editor)$, float on
windowrule = match:class ^(org.Waytrogen.Waytrogen)$, float on
windowrule = match:class ^(waytrogen)$, float on
windowrule = match:class ^(com.github.unrud.VideoDownloader)$, float on
windowrule = match:class ^(com.interversehq.qView)$, float on

# MPD cover art (imv)
windowrule = match:class ^(imv)$, float on
windowrule = match:class ^(imv)$, size 300 300
windowrule = match:class ^(imv)$, move 100%-320 100%-320
windowrule = match:class ^(imv)$, pin on