source = $HOME/.config/hypr/config/variables.conf
# Fix some dragging issues with XWayland
windowrule = match:class ^$, match:title ^$, match:xwayland true, no_focus on
# No blur for empty class/title
windowrule = match:class ^()$, match:title ^()$, no_blur on
