source = $HOME/.config/hypr/config/variables.conf

# LAYER RULES
layerrule = blur on, match:namespace wofi
layerrule = xray 1, match:namespace wofi
layerrule = dim_around on, match:namespace wofi
layerrule = ignore_alpha 0, match:namespace wofi
layerrule = ignore_alpha 0.9, match:namespace wofi

# waybar blur disabled - using solid pills instead
# layerrule = blur on, match:namespace waybar
# layerrule = xray 1, match:namespace waybar
# layerrule = ignore_zero on, match:namespace waybar
# layerrule = blur_popups on, match:namespace waybar

layerrule = no_anim on, match:namespace hyprswitch

layerrule = blur on, match:namespace swaync-notification-window
layerrule = blur on, match:namespace swaync-control-center
layerrule = xray 1, match:namespace swaync-notification-window
layerrule = xray 1, match:namespace swaync-control-center
layerrule = ignore_alpha 0, match:namespace swaync-notification-window
layerrule = ignore_alpha 0, match:namespace swaync-control-center
layerrule = ignore_alpha 0.45, match:namespace swaync-control-center
layerrule = ignore_alpha 0.45, match:namespace swaync-notification-window
layerrule = animation slide right, match:namespace swaync-control-center

layerrule = blur on, match:namespace logout_dialog
