source = $HOME/.config/hypr/config/variables.conf

# PICTURE-IN-PICTURE (PIP) RULES
windowrule = match:class (firefox|google-chrome|zen), match:title .*(Picture-in-Picture|Picture in Picture).*, float on
windowrule = match:class (firefox|google-chrome|zen), match:title .*(Picture-in-Picture|Picture in Picture).*, pin on
windowrule = match:class (firefox|google-chrome|zen), match:title .*(Picture-in-Picture|Picture in Picture).*, size 480 270
windowrule = match:class (firefox|google-chrome|zen), match:title .*(Picture-in-Picture|Picture in Picture).*, no_blur on
windowrule = match:class (firefox|google-chrome|zen), match:title .*(Picture-in-Picture|Picture in Picture).*, move 74.5% 4.25%
windowrule = match:class (firefox|google-chrome|zen), match:title .*(Picture-in-Picture|Picture in Picture).*, animation slide
windowrule = match:class (firefox|google-chrome|zen), match:title .*(Picture-in-Picture|Picture in Picture).*, opaque on

# Image viewer Qview
windowrule = match:class (com.interversehq.qView), opaque on