source = $HOME/.config/hypr/config/variables.conf

# OPACITY WINDOW RULES
windowrule = match:class ^(hyprswitch)$, opacity $opacityFloat $opacityFloat
# windowrule = match:class ^(Dunst)$, opacity $opacityFloat $opacityFloat
windowrule = match:class ^(thunar)$, opacity $opacityFloat $opacityFloat
windowrule = match:class ^(code)$, opacity $opacityFloat $opacityFloat
windowrule = match:class ^(cursor)$, opacity $opacityFloat $opacityFloat
windowrule = match:class ^(kiro-url-handler)$, opacity $opacityFloat $opacityFloat
windowrule = match:title ^(nvim.*)$, opacity $opacityFloat $opacityFloat
windowrule = match:title ^(zsh*)$, opacity $opacityFloat $opacityFloat

# Special opacity for typing test
windowrule = match:class (zen), match:title ^(Monkeytype.*)$, opacity 0.75 0.75